import Sidebar from "@/components/Sidebar";
import classnames from "classnames";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amane Kanata's 4th Anniversary Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyClass = classnames(inter.className, "flex mx-auto w-full");
  return (
    <html lang="en">
      <body className={bodyClass}>
        <div>
          <Sidebar />
        </div>
        <main className="w-full">{children}</main>
      </body>
    </html>
  );
}
